import { describe,it,expect,vi } from 'vitest';
import { seedWorkspace } from '../../src/domain/fixtures';
import { importInvoices,parseCsv } from '../../src/domain/accounting';
import { extractionSchema,validateExtraction,qualityRubric,safeUrl,retry,EXTRACTION_VERSION } from '../../src/server/providers';
import { assertOrigin,requireAdmin } from '../../src/server/store';
const w=seedWorkspace();
describe('provider and import boundaries',()=>{
  it('preserves generic service as unknown, with exact legal match',()=>{const rows=importInvoices('invoice_id,legal_id,service_id,description,amount,currency,date\nI1,DEMO-RO-001,,IT services,1200,EUR,2026-09-01',w.companies,w.services,'hash',true);expect(rows[0].companyId).toBe('atlas');expect(rows[0].serviceId).toBeNull();});
  it('never joins ambiguous entities',()=>{expect(importInvoices('invoice_id,legal_id,service_id,description,amount,currency,date\nI1,NOT-MATCHED,,IT services,1200,EUR,2026-09-01',w.companies,w.services,'hash',true)[0].companyId).toBeNull();});
  it('rejects malformed invoice dates',()=>{expect(()=>importInvoices('invoice_id,legal_id,service_id,description,amount,currency,date\nI1,ID,,IT,10,EUR,2026-02-31',w.companies,w.services,'hash',true)).toThrow();});
  it('parses quoted commas, escaped quotes and newlines',()=>{expect(parseCsv('a,b\n"one,two","say ""hi""\nnext"')).toEqual([['a','b'],['one,two','say "hi"\nnext']]);expect(()=>parseCsv('"unclosed')).toThrow();});
  it('rejects unknown service and duplicate invoice IDs',()=>{expect(()=>importInvoices('invoice_id,legal_id,service_id,description,amount,currency,date\nI1,ID,bad,IT,10,EUR,2026-09-01',w.companies,w.services,'h',true)).toThrow();expect(()=>importInvoices('invoice_id,legal_id,service_id,description,amount,currency,date\nI1,ID,,IT,10,EUR,2026-09-01\nI1,ID,,IT,10,EUR,2026-09-02',w.companies,w.services,'h',true)).toThrow('Duplicate invoice ID');});
  it('schema rejects malformed extraction',()=>{expect(extractionSchema.safeParse({answers:[{answer:'maybe'}]}).success).toBe(false);});
  it('withholds invented quotes and invalid dates',()=>{const input={answers:[{questionId:w.services[0].questions[0].id,answer:'yes' as const,quote:'invented quote',eventDate:'2026-02-31',eventSummary:'event',companyNamed:true,reason:'test'}]};const e=validateExtraction(input,w.companies[0],w.services[0],'actual text','https://example.com/news','2026-09-26T00:00:00Z','test')[0];expect(e.answer).toBe('unknown');expect(e.eventDate).toBeNull();expect(e.status).toBe('review');});
  it('cannot promote unassigned company evidence',()=>{const quote='We are hiring security specialists';const input={answers:[{questionId:w.services[0].questions[0].id,answer:'yes' as const,quote,eventDate:null,eventSummary:'event',companyNamed:false,reason:'identity unclear'}]};expect(validateExtraction(input,w.companies[0],w.services[0],quote,'https://example.com','2026-09-26T00:00:00Z','test')[0].status).toBe('review');});
  it('rejects private, credentialed and non-HTTPS source URLs',()=>{for(const url of ['http://example.com','https://127.0.0.1','https://[::1]','https://localhost','https://user:password@example.com','https://example.com:8080','https://intranet.local'])expect(()=>safeUrl(url)).toThrow();expect(safeUrl('https://example.com/news').hostname).toBe('example.com');});
  // Fake timers only speed this up under vitest; with real timers (sandbox shim) the backoff is 400ms + 800ms and the test still completes.
  it('retries 429 with bounds, but never a denied request',async()=>{vi.useFakeTimers();try{let calls=0;const p=retry(async()=>{calls++;if(calls<3)throw {status:429};return 'ok';});await vi.runAllTimersAsync();expect(await p).toBe('ok');expect(calls).toBe(3);}finally{vi.useRealTimers();}let denied=0;await expect(retry(async()=>{denied++;throw {status:403};})).rejects.toEqual({status:403});expect(denied).toBe(1);});
  it('denies cross-origin and read-only role writes',()=>{expect(()=>assertOrigin(new Request('https://app.example/api',{headers:{origin:'https://evil.example'}}))).toThrow();expect(()=>requireAdmin({tenant:'a',user:'b',role:'sales',mode:'live'})).toThrow();});
});
const svc=w.services[0],co=w.companies[0],at='2026-09-26T00:00:00Z',url='https://example.com/news';
const ans=(o:Partial<{questionId:string;answer:'yes'|'no'|'unknown'|'conflict';quote:string;eventDate:string|null;eventSummary:string;companyNamed:boolean;reason:string;claimType:'plan'|'fact'|'possibility'|'historical';polarity:'positive'|'negative'|'neutral';sourceType:'procurement'|'career_page'|'news'}>)=>({questionId:svc.questions[0].id,answer:'yes' as const,quote:'We are hiring an ISO 27001 lead auditor',eventDate:'2026-09-01',eventSummary:'ISO 27001 lead auditor hiring',companyNamed:true,reason:'explicit role',...o});
const TEXT='Atlas Manufacturing: We are hiring an ISO 27001 lead auditor for our NIS2 programme.';
describe('v7 extraction validation and quality rubric',()=>{
  it('uses the v7 SCUT NIS2 service with grc-hiring first',()=>{expect(svc.id).toBe('scut-nis2');expect(svc.questions[0].id).toBe('grc-hiring');});
  it('validates an explicit, dated, company-named quote',()=>{const e=validateExtraction({answers:[ans({})]},co,svc,TEXT,url,at,'m')[0];expect(e.answer).toBe('yes');expect(e.status).toBe('validated');expect(e.eventDate).toBe('2026-09-01');});
  it('never counts historical activity as a current signal',()=>{const e=validateExtraction({answers:[ans({claimType:'historical'})]},co,svc,TEXT,url,at,'m')[0];expect(e.answer).toBe('unknown');expect(e.status).toBe('review');expect(e.reason.startsWith('Historical activity')).toBe(true);expect(e.claimType).toBe('historical');});
  it('quality rubric: procurement baseline and bounded penalties',()=>{expect(qualityRubric('procurement',true,true,true)).toBe(1);expect(qualityRubric('procurement',false,true,true)).toBeCloseTo(0.7,5);expect(qualityRubric('procurement',true,false,true)).toBeCloseTo(0.7,5);expect(qualityRubric('procurement',true,true,false)).toBeCloseTo(0.9,5);
    for(const t of ['procurement','registry','newsroom','news','job_board','other','nonsense'])for(const a of [true,false])for(const b of [true,false])for(const c of [true,false]){const q=qualityRubric(t,a,b,c);expect(q).toBeGreaterThanOrEqual(0);expect(q).toBeLessThanOrEqual(1);}
    expect(qualityRubric('other',false,false,false)).toBe(0);});
  it('evidence carries category, sourceType, polarity, claimType and versions',()=>{const e=validateExtraction({answers:[ans({sourceType:'career_page',polarity:'positive',claimType:'plan'})]},co,svc,TEXT,url,at,'m')[0];expect(e.category).toBe(svc.questions[0].category);expect(e.sourceType).toBe('career_page');expect(e.polarity).toBe('positive');expect(e.claimType).toBe('plan');expect(e.extractionVersion).toBe('sales-signals-v2');expect(EXTRACTION_VERSION).toBe('sales-signals-v2');expect(e.ruleVersion).toBe(svc.version);expect(e.quality).toBe(0.85);});
  it('omitted questions become inspectable unknown rows, never inferred answers',()=>{const rows=validateExtraction({answers:[ans({})]},co,svc,TEXT,url,at,'m');const enabled=svc.questions.filter(q=>q.enabled);expect(rows).toHaveLength(enabled.length);expect(new Set(rows.map(r=>r.questionId)).size).toBe(enabled.length);
    const omitted=rows.filter(r=>r.questionId!==svc.questions[0].id);expect(omitted).toHaveLength(enabled.length-1);for(const r of omitted){expect(r.answer).toBe('unknown');expect(r.status).toBe('review');expect(r.quote).toBe('');expect(r.eventDate).toBeNull();expect(r.quality).toBe(0);expect(r.reason).toContain('omitted');expect(r.category).toBe(svc.questions.find(q=>q.id===r.questionId)!.category);}});
  it('eventKey is stable per company+event+date and changes with the date',()=>{const k=(text:string,d:string)=>validateExtraction({answers:[ans({eventDate:d})]},co,svc,text,url,at,'m')[0].eventKey;
    const a=k(TEXT,'2026-09-01'),b=k(TEXT+' Republished by a job board.','2026-09-01'),c=k(TEXT,'2026-09-02');expect(a).toBe(b);expect(a===c).toBe(false);});
});
